name: Main branch workflow

on:
  push:
    branches:
      - 'jitpack-cd'

permissions:
  contents: write

jobs:
  main-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Create new tag
        id: create_tag
        uses: ./.github/workflows/create-new-tag.yml
        with:
          branch: 'main'

      - name: Create new release
        uses: ./.github/workflows/create-new-release.yml
        with:
          tag_name: ${{ jobs.main-workflow.steps.create_tag.outputs.tag_name }}
