name: Main Workflow

on:
  push:
    branches:
      - 'jitpack-cd'

permissions:
  contents: write

jobs:
  independent-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print message
        run: echo "This is an independent job"

  handle-new-tag:
    uses: ./.github/workflows/new-tag.yml

  handle-new-release:
    uses: ./.github/workflows/new-release.yml