name: Create new release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-new-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Read release body from file
        id: read_release_body
        run: |
          echo "RELEASE_BODY=$(cat release-notes.txt)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: 'Auto OTP Reader ${{ inputs.tag_name }}'
          body: ${{ env.RELEASE_BODY }}
          draft: false
          prerelease: false
