name: Create new tag on push on jitpack-cd branch

on:
  push:
    branches:
      - 'jitpack-cd'

permissions:
  contents: write

jobs:
  create-new-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@2.5.0

      - name: Check for existing tag
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${{ steps.get_next_version.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag already exists"
            exit 1
          fi

      - name: Create new tag
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' && steps.check_tag.outcome != 'failure' }}
        run: |
          git tag ${{ steps.get_next_version.outputs.version }}
          git push origin ${{ steps.get_next_version.outputs.version }}